services:
  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@123
      - POSTGRES_DB=default
    ports:
      - 5432:5432