services:
  
  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@123
      - POSTGRES_DB=default
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  keycloak:
    depends_on:
      - postgres
    container_name: keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: products
      DB_USER: admin
      DB_PASSWORD: admin@123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin@123
    image: quay.io/keycloak/keycloak
    command: start-dev
    ports:
      - "8081:8080"
  
  server:
    build:
      dockerfile: ./Dockerfile
      context: ./server
    container_name: server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/products
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin@123
    ports:
      - 8080:8080

volumes:
  data: